on: [push, pull_request_target]
name: build
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
      - name: Build
        run: go build
      - name: Build CMD
        run: cd cmd/commandline; go build; cd ../../
      - name: Test
        run: go test -v -coverprofile=coverage.out ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
         file: ./coverage.out
         env_vars: OS
         flags: unittests
         name: $(git rev-parse --short "$GITHUB_SHA")
         fail_ci_if_error: true
